services:
  app:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: tinnova_frontend
    ports:
      - "${APP_PORT:-3000}:3000"
      - "5173:5173"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      VITE_URL_MOCK: ${VITE_URL_MOCK}
    volumes:
      - ./application:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
